spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/digital_avatars?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver